version: "3.8"

services:
  adonis:
    build:
      context: .
      dockerfile: Dockerfile
      
    container_name: adonis_app
    restart: always
   
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=localhost
      - LOG_LEVEL=info
      - APP_KEY=your_generated_key_here
      - NODE_ENV=development
      - SESSION_DRIVER=cookie
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=6033
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=db_flashCards
   
    
    working_dir: /flashcards

    command: dumb-init node ace serve --watch 
  mysql:
    image: mysql:8.0.30
    container_name: db_FlashCards
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_DATABASE: app
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/scripts

volumes:
  mysql_data:
