version: '3.8'

services:
  adonis_app:
    container_name: adonis
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
