services:
  db:
    image: mysql:8.0.30
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - '6033:3306'
    volumes:
      - dbdata:/var/lib/mysql

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - mysql
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333

    env_file:
      - .env
    environment:
      - NODE_ENV=production

    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  dbdata:
