version: '3.8'

services:
  mysql-app:
    container_name: flashCards-db
    image: mysql:latest
    ports:
      - '6033:3306'
    environment:
      MYSQL_DATABASE: 'db_flashCards'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    networks:
      flashcards-network:
        ipv4_address: 172.16.1.20

  vue-app:
    container_name: flashCards-app
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      TZ: UTC
      PORT: 3333
      HOST: 172.16.1.20
      LOG_LEVEL: info
      APP_KEY: -yX1-AMF7mEnfKjHZ5olTm4Lf9nVQfnJ
      SESSION_DRIVER: cookie
      DB_CONNECTION: mysql
      DB_HOST: 172.16.1.20
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: db_flashCards
    stdin_open: true
    tty: true
    entrypoint: ['./entrypoint.sh']
    networks:
      flashcards-network:
        ipv4_address: 172.16.1.10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: flashcard_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db

networks:
  flashcards-network:
    ipam:
      driver: default
      config:
        - subnet: '172.16.1.0/24'
